/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitVisitIdRouteImport } from './routes/visit.$visitId'
import { Route as VisitCompleteVisitIdRouteImport } from './routes/visit-complete.$visitId'
import { Route as MapVisitIdRouteImport } from './routes/map.$visitId'
import { Route as PlayerVisitIdStepIndexRouteImport } from './routes/player.$visitId.$stepIndex'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitVisitIdRoute = VisitVisitIdRouteImport.update({
  id: '/visit/$visitId',
  path: '/visit/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitCompleteVisitIdRoute = VisitCompleteVisitIdRouteImport.update({
  id: '/visit-complete/$visitId',
  path: '/visit-complete/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const MapVisitIdRoute = MapVisitIdRouteImport.update({
  id: '/map/$visitId',
  path: '/map/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerVisitIdStepIndexRoute = PlayerVisitIdStepIndexRouteImport.update({
  id: '/player/$visitId/$stepIndex',
  path: '/player/$visitId/$stepIndex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/visits': typeof VisitsRoute
  '/map/$visitId': typeof MapVisitIdRoute
  '/visit-complete/$visitId': typeof VisitCompleteVisitIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/player/$visitId/$stepIndex': typeof PlayerVisitIdStepIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/visits': typeof VisitsRoute
  '/map/$visitId': typeof MapVisitIdRoute
  '/visit-complete/$visitId': typeof VisitCompleteVisitIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/player/$visitId/$stepIndex': typeof PlayerVisitIdStepIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/visits': typeof VisitsRoute
  '/map/$visitId': typeof MapVisitIdRoute
  '/visit-complete/$visitId': typeof VisitCompleteVisitIdRoute
  '/visit/$visitId': typeof VisitVisitIdRoute
  '/player/$visitId/$stepIndex': typeof PlayerVisitIdStepIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/visits'
    | '/map/$visitId'
    | '/visit-complete/$visitId'
    | '/visit/$visitId'
    | '/player/$visitId/$stepIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/visits'
    | '/map/$visitId'
    | '/visit-complete/$visitId'
    | '/visit/$visitId'
    | '/player/$visitId/$stepIndex'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/visits'
    | '/map/$visitId'
    | '/visit-complete/$visitId'
    | '/visit/$visitId'
    | '/player/$visitId/$stepIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VisitsRoute: typeof VisitsRoute
  MapVisitIdRoute: typeof MapVisitIdRoute
  VisitCompleteVisitIdRoute: typeof VisitCompleteVisitIdRoute
  VisitVisitIdRoute: typeof VisitVisitIdRoute
  PlayerVisitIdStepIndexRoute: typeof PlayerVisitIdStepIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit/$visitId': {
      id: '/visit/$visitId'
      path: '/visit/$visitId'
      fullPath: '/visit/$visitId'
      preLoaderRoute: typeof VisitVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit-complete/$visitId': {
      id: '/visit-complete/$visitId'
      path: '/visit-complete/$visitId'
      fullPath: '/visit-complete/$visitId'
      preLoaderRoute: typeof VisitCompleteVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/$visitId': {
      id: '/map/$visitId'
      path: '/map/$visitId'
      fullPath: '/map/$visitId'
      preLoaderRoute: typeof MapVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$visitId/$stepIndex': {
      id: '/player/$visitId/$stepIndex'
      path: '/player/$visitId/$stepIndex'
      fullPath: '/player/$visitId/$stepIndex'
      preLoaderRoute: typeof PlayerVisitIdStepIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VisitsRoute: VisitsRoute,
  MapVisitIdRoute: MapVisitIdRoute,
  VisitCompleteVisitIdRoute: VisitCompleteVisitIdRoute,
  VisitVisitIdRoute: VisitVisitIdRoute,
  PlayerVisitIdStepIndexRoute: PlayerVisitIdStepIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
